title: Building an android application
author: Shahnawaz ali
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is meant to give an introduction to a beginner, to create an androd application in easy steps.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
